### ISSUE TITLE
Add a font-kit support

### ISSUE THREAD

**Issue by RazrFalcon** [manuel-rhdt/harfbuzz_rs#12]
https://github.com/pcwalton/font-kit

**Comment by manuel-rhdt** [comment]
What exactly are you expecting here?

**Comment by RazrFalcon** [comment]
Probably nothing =)

I thought that `rusttype` is used for fonts handling, but turns out that `harfbuzz` handles them itself. I was simply confused by the `rusttype` dependency.

**Comment by manuel-rhdt** [comment]
Harfbuzz is actually very flexible and you can use any backend you want to access fonts. This is exposed through the `FontFuncs` trait and `.set_font_funcs()` method on `Font`  😊.

**Comment by RazrFalcon** [comment]
Let's say I want to shape text and then extract required glyph outlines. Currently, the font is loaded twice: 
- once for `font-kit` which I'm using for font matching and glyph extraction
- once for harfbuzz (via freetype on linux, I presume)

Can I use font loaded by `font-kit`?

**Comment by manuel-rhdt** [comment]
You create the harfbuzz `Face` from the bytes provided by font-kit's [`copy_font_data`](https://docs.rs/font-kit/0.1.0/font_kit/loaders/freetype/struct.Font.html#method.copy_font_data).

Harfbuzz will not need FreeType to do the shaping.

**Comment by RazrFalcon** [comment]
Yes, it works. Thanks.
