### ISSUE TITLE
Wrap/hide all FFI structs

### ISSUE THREAD

**Issue by RazrFalcon** [manuel-rhdt/harfbuzz_rs#13]
Like `hb::hb_direction_t`, `hb::hb_script_t`, etc.

Also, methods like `UnicodeBuffer::set_direction` require private types, since `hb` namespace isn't public.

**Comment by manuel-rhdt** [comment]
I think you can use these by using harfbuzz_sys yourself as a dependency. But that is ugly and shouldn't be so. Will look into it.

**Comment by RazrFalcon** [comment]
What about `hb::hb_feature_t`?

**Comment by RazrFalcon** [comment]
Thanks!
