### ISSUE TITLE
UnicodeBuffer::add_str does not allow adding subitems

### ISSUE THREAD

**Issue by khaledhosny** [manuel-rhdt/harfbuzz_rs#15]
The HarfBuzz C API takes a pointer to text, its length, and start and length of subitem (run) being shaped, and this is important when shaping parts of larger text. The rust API takes only a string, so one can only the part being shaped without the rest of its context (which prevents HarfBuzz from doing things like Arabic shaping across runs of text).

**Comment by manuel-rhdt** [comment]
Thanks for the issue. I missed that capability of harfbuzz. I will think of how to incorporate adequate changes into the wrapper.

**Comment by khaledhosny** [comment]
Thanks!
