### ISSUE TITLE
The minimum harfbuzz version

### ISSUE THREAD

**Issue by RazrFalcon** [manuel-rhdt/harfbuzz_rs#17]
You are using `hb_ot_font_set_funcs`, which was added in v0.9.28, but Ubuntu 14.04, which is used in Travis CI, is using v0.9.27.

So I think that the minimal required harfbuzz version should be noted in the readme.

Or maybe we can remove it completely, since:

>Note that fonts returned by hb_font_create() default to using these functions, so most clients would never need to call these functions directly.

**Comment by manuel-rhdt** [comment]
I am sorry to have ignored this issue for so long. This library is intended to be used with "new" releases of harfbuzz, i.e. version 2 and up. I will make that clearer. Thank you for filing the issue and your patience!
