### ISSUE TITLE
ARM-based build issues

### ISSUE THREAD

**Issue by ndowens** [manuel-rhdt/harfbuzz_rs#21]
When building a pkg on aarch64 armv7l armv6l that uses harfbuzz_rs I get:
 Compiling harfbuzz_rs v1.0.0

error[E0308]: mismatched types

  --> /tmp/.cargo/registry/src/github.com-1ecc6299db9ec823/harfbuzz_rs-1.0.0/src/blob.rs:42:17

   |

42 |                 bytes.as_ptr() as *const i8,

   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u8, found i8

   |

   = note: expected type `*const u8`

              found type `*const i8`

error[E0308]: mismatched types

  --> /tmp/.cargo/registry/src/github.com-1ecc6299db9ec823/harfbuzz_rs-1.0.0/src/blob.rs:57:17

   |

57 |                 bytes.as_ptr() as *const i8,

   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u8, found i8

   |

   = note: expected type `*const u8`

              found type `*const i8`

error[E0308]: mismatched types

   --> /tmp/.cargo/registry/src/github.com-1ecc6299db9ec823/harfbuzz_rs-1.0.0/src/blob.rs:207:17

    |

207 |                 ptr as *const i8,

    |                 ^^^^^^^^^^^^^^^^ expected u8, found i8

    |

    = note: expected type `*const u8`

               found type `*const i8`

error[E0308]: mismatched types

   --> /tmp/.cargo/registry/src/github.com-1ecc6299db9ec823/harfbuzz_rs-1.0.0/src/buffer.rs:150:17

    |

150 |                 utf8_ptr,

    |                 ^^^^^^^^ expected u8, found i8

    |

    = note: expected type `*const u8`

               found type `*const i8`

error: aborting due to 4 previous errors

**Comment by meisterluk** [comment]
Hi @ndowens! Would you mind improving the readability of your issue? By wrapping your error message with ` ``` `, you will make the error message more readable.

**Comment by bluekyu** [comment]
This may be fixed by https://github.com/manuel-rhdt/harfbuzz_rs/commit/8ddd850129e23e768dfc2d9435da7f8bb4e768f2.
