### ISSUE TITLE
GlyphBuffer::serializer returns an empty string when contains a single glyph

### ISSUE THREAD

**Issue by RazrFalcon** [manuel-rhdt/harfbuzz_rs#23]
https://github.com/manuel-rhdt/harfbuzz_rs/blob/cf1b525397ee3360ab2087d2bd7f784bdf0fe7ab/src/buffer.rs#L324

I guess in this line we should use just `>`.

**Comment by manuel-rhdt** [comment]
Thank you for this issue!

**Comment by RazrFalcon** [comment]
No problem. Would you plan to release a new version soon?

**Comment by manuel-rhdt** [comment]
Doing it right now 👍

**Comment by RazrFalcon** [comment]
Thanks!
