### ISSUE TITLE
How to force static linking on linux?

### ISSUE THREAD

**Issue by RazrFalcon** [manuel-rhdt/harfbuzz_rs#25]
I want to use a statically linked version on linux, instead of a system one.

**Comment by manuel-rhdt** [comment]
The bindings to the harfbuzz native library is handled by harfbuzz_sys. By reading through the their [build.rs](https://github.com/servo/rust-harfbuzz/blob/master/harfbuzz-sys/build.rs) file it seems like two conditions need to be fulfilled:
1. The harfbuzz_sys feature `build-native-harfbuzz` must be enabled (which it should be by default)
2. The environment variable `HARFBUZZ_SYS_NO_PKG_CONFIG` must be set to some arbitrary value

So I suggest you try to build with the environment `HARFBUZZ_SYS_NO_PKG_CONFIG=1` and see whether that works.

**Comment by RazrFalcon** [comment]
Thanks, it worked. But can it be set via cargo feature somehow?

But I guess it should be asked in the `rust-harfbuzz` repo.
