### ISSUE TITLE
Bad font data causes panic, not error

### ISSUE THREAD

**Issue by jimblandy** [manuel-rhdt/harfbuzz_rs#5]
I tried the first code example in the doc introduction using the [Inconsolata][inc] font, and got a panic. I changed the code to read `main.rs` as the font data, and got the same panic:
```
extern crate harfbuzz_rs;

use harfbuzz_rs::*;
use harfbuzz_rs::rusttype::SetRustTypeFuncs;

use std::path::{Path, PathBuf};

fn main() {
    let face = Face::from_file("main.rs", 0)
        .expect("failed to parse Face from file");
    let mut font = Font::new(face);
    font.set_rusttype_funcs();

    let output = UnicodeBuffer::new().add_str("Hello, world!").shape(&font, &[]);
}
```
This panics at the `unwrap` in `rusttype_font_from_face`:
```
	    collection.font_at(index as usize).unwrap()
```
It would be nice to have a fallible interface that could distinguish between invalid font data, a bad index into the collection, and so on.

[inc]: http://levien.com/type/myfonts/Inconsolata.otf

**Comment by manuel-rhdt** [comment]
You are right of course! I will try to improve this soon. Pull requests welcome!

**Comment by manuel-rhdt** [comment]
In #6 I have added error handling for the `set_rusttype_funcs` method. However RustType itself doesn't provide detailed errors, so I'm afraid this crate can't provide better error messages at the moment.
